import { createFileRoute, Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Boxes, CalendarClock, ClipboardList, Sparkles, Waves } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Plant Maintenance | Wastewater Asset & Work Order System" },
      {
        name: "description",
        content:
          "Wastewater plant CMMS: 1,160 assets with nameplate data, PM schedules, manufacturer maintenance lookups, and work orders.",
      },
      { property: "og:title", content: "Plant Maintenance | Wastewater Asset & Work Order System" },
      {
        property: "og:description",
        content: "Assets, PM schedules, manufacturer maintenance data, and work orders for your treatment plant.",
      },
    ],
  }),
  component: Landing,
});

const FEATURES = [
  {
    icon: Boxes,
    title: "Asset register",
    body: "Every pump, motor, blower, and panel imported from your spreadsheet with make, model, serial, HP, volts, RPM, frame, and location.",
  },
  {
    icon: CalendarClock,
    title: "PM schedules",
    body: "Preventive programs seeded by equipment class with intervals, next-due tracking, and one-click completion that reschedules the task.",
  },
  {
    icon: Sparkles,
    title: "Manufacturer lookups",
    body: "Pull published O&M intervals, wear parts, and manual links for a specific make and model straight onto the asset record.",
  },
  {
    icon: ClipboardList,
    title: "Work orders",
    body: "Write corrective, preventive, or emergency work orders against any asset or PM, with priority, due date, and status tracking.",
  },
];

function Landing() {
  return (
    <div className="min-h-screen">
      <header className="border-b border-sidebar-border bg-sidebar text-sidebar-foreground">
        <div className="mx-auto flex h-14 max-w-6xl items-center justify-between px-4">
          <div className="flex items-center gap-2">
            <Waves className="size-5 text-sidebar-primary" />
            <span className="text-sm font-bold uppercase tracking-widest">Plant Maintenance</span>
          </div>
          <Link to="/auth">
            <Button size="sm" variant="secondary">
              Sign in
            </Button>
          </Link>
        </div>
      </header>

      <section className="border-b border-border bg-sidebar text-sidebar-foreground">
        <div className="mx-auto max-w-6xl px-4 py-20">
          <p className="font-mono text-xs uppercase tracking-[0.2em] text-sidebar-primary">
            Wastewater treatment · maintenance operations
          </p>
          <h1 className="mt-4 max-w-3xl text-4xl font-bold leading-tight sm:text-5xl">
            Your plant's assets, PM program, and work orders in one system.
          </h1>
          <p className="mt-5 max-w-2xl text-sm text-sidebar-foreground/70 sm:text-base">
            Built from your existing asset export — 1,160 assets with full nameplate data, PM schedules generated by
            equipment class, manufacturer maintenance research on demand, and work orders your crew can act on today.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <Link to="/auth">
              <Button size="lg">Open the control room</Button>
            </Link>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-4 py-16">
        <h2 className="text-xl font-bold">What's inside</h2>
        <div className="mt-6 grid gap-4 sm:grid-cols-2">
          {FEATURES.map((f) => (
            <div key={f.title} className="panel p-5">
              <f.icon className="size-5 text-primary" />
              <h3 className="mt-3 text-base font-semibold">{f.title}</h3>
              <p className="mt-1.5 text-sm text-muted-foreground">{f.body}</p>
            </div>
          ))}
        </div>
      </section>

      <footer className="border-t border-border py-8">
        <p className="mx-auto max-w-6xl px-4 font-mono text-xs text-muted-foreground">
          Plant maintenance management system
        </p>
      </footer>
    </div>
  );
}
