/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedManualsRouteImport } from './routes/_authenticated/manuals'
import { Route as AuthenticatedPartRequestsRouteImport } from './routes/_authenticated/part-requests'
import { Route as AuthenticatedPmScheduleRouteImport } from './routes/_authenticated/pm-schedule'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedWorkOrdersRouteImport } from './routes/_authenticated/work-orders'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets.index'
import { Route as AuthenticatedAssetsAssetIdRouteImport } from './routes/_authenticated/assets.$assetId'
import { Route as AuthenticatedAssetsCaptureRouteImport } from './routes/_authenticated/assets.capture'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManualsRoute = AuthenticatedManualsRouteImport.update({
  id: '/manuals',
  path: '/manuals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartRequestsRoute =
  AuthenticatedPartRequestsRouteImport.update({
    id: '/part-requests',
    path: '/part-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPmScheduleRoute = AuthenticatedPmScheduleRouteImport.update({
  id: '/pm-schedule',
  path: '/pm-schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkOrdersRoute = AuthenticatedWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsAssetIdRoute =
  AuthenticatedAssetsAssetIdRouteImport.update({
    id: '/assets/$assetId',
    path: '/assets/$assetId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsCaptureRoute =
  AuthenticatedAssetsCaptureRouteImport.update({
    id: '/assets/capture',
    path: '/assets/capture',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/manuals': typeof AuthenticatedManualsRoute
  '/part-requests': typeof AuthenticatedPartRequestsRoute
  '/pm-schedule': typeof AuthenticatedPmScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/assets/$assetId': typeof AuthenticatedAssetsAssetIdRoute
  '/assets/capture': typeof AuthenticatedAssetsCaptureRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/manuals': typeof AuthenticatedManualsRoute
  '/part-requests': typeof AuthenticatedPartRequestsRoute
  '/pm-schedule': typeof AuthenticatedPmScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/assets/$assetId': typeof AuthenticatedAssetsAssetIdRoute
  '/assets/capture': typeof AuthenticatedAssetsCaptureRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/manuals': typeof AuthenticatedManualsRoute
  '/_authenticated/part-requests': typeof AuthenticatedPartRequestsRoute
  '/_authenticated/pm-schedule': typeof AuthenticatedPmScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/work-orders': typeof AuthenticatedWorkOrdersRoute
  '/_authenticated/assets/$assetId': typeof AuthenticatedAssetsAssetIdRoute
  '/_authenticated/assets/capture': typeof AuthenticatedAssetsCaptureRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/approvals'
    | '/dashboard'
    | '/inventory'
    | '/manuals'
    | '/part-requests'
    | '/pm-schedule'
    | '/settings'
    | '/team'
    | '/work-orders'
    | '/assets/$assetId'
    | '/assets/capture'
    | '/assets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/approvals'
    | '/dashboard'
    | '/inventory'
    | '/manuals'
    | '/part-requests'
    | '/pm-schedule'
    | '/settings'
    | '/team'
    | '/work-orders'
    | '/assets/$assetId'
    | '/assets/capture'
    | '/assets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/approvals'
    | '/_authenticated/dashboard'
    | '/_authenticated/inventory'
    | '/_authenticated/manuals'
    | '/_authenticated/part-requests'
    | '/_authenticated/pm-schedule'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/work-orders'
    | '/_authenticated/assets/$assetId'
    | '/_authenticated/assets/capture'
    | '/_authenticated/assets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manuals': {
      id: '/_authenticated/manuals'
      path: '/manuals'
      fullPath: '/manuals'
      preLoaderRoute: typeof AuthenticatedManualsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/part-requests': {
      id: '/_authenticated/part-requests'
      path: '/part-requests'
      fullPath: '/part-requests'
      preLoaderRoute: typeof AuthenticatedPartRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pm-schedule': {
      id: '/_authenticated/pm-schedule'
      path: '/pm-schedule'
      fullPath: '/pm-schedule'
      preLoaderRoute: typeof AuthenticatedPmScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-orders': {
      id: '/_authenticated/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof AuthenticatedWorkOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/$assetId': {
      id: '/_authenticated/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AuthenticatedAssetsAssetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/capture': {
      id: '/_authenticated/assets/capture'
      path: '/assets/capture'
      fullPath: '/assets/capture'
      preLoaderRoute: typeof AuthenticatedAssetsCaptureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedManualsRoute: typeof AuthenticatedManualsRoute
  AuthenticatedPartRequestsRoute: typeof AuthenticatedPartRequestsRoute
  AuthenticatedPmScheduleRoute: typeof AuthenticatedPmScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedWorkOrdersRoute: typeof AuthenticatedWorkOrdersRoute
  AuthenticatedAssetsAssetIdRoute: typeof AuthenticatedAssetsAssetIdRoute
  AuthenticatedAssetsCaptureRoute: typeof AuthenticatedAssetsCaptureRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedManualsRoute: AuthenticatedManualsRoute,
  AuthenticatedPartRequestsRoute: AuthenticatedPartRequestsRoute,
  AuthenticatedPmScheduleRoute: AuthenticatedPmScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedWorkOrdersRoute: AuthenticatedWorkOrdersRoute,
  AuthenticatedAssetsAssetIdRoute: AuthenticatedAssetsAssetIdRoute,
  AuthenticatedAssetsCaptureRoute: AuthenticatedAssetsCaptureRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
